"""empty message

Revision ID: 02702b6f88ce
Revises: 7c7072ff019d
Create Date: 2023-03-02 13:37:48.161212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02702b6f88ce'
down_revision = '7c7072ff019d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas', schema=None) as batch_op:
        batch_op.drop_column('aforo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aforo', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
