"""empty message

Revision ID: 2fb74f4256c6
Revises: 
Create Date: 2023-02-26 16:51:27.890129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb74f4256c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_espacioFisico', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Integer(), nullable=True),
    sa.Column('vencida', sa.Integer(), nullable=True),
    sa.Column('fecha_realizada', sa.String(), nullable=True),
    sa.Column('fecha_vencimiento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    # ### end Alembic commands ###
