"""empty message

Revision ID: 541e09d525e9
Revises: 5f5ce4efde3e
Create Date: 2023-03-05 18:45:14.988823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541e09d525e9'
down_revision = '5f5ce4efde3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espacios_fisicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aforo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espacios_fisicos', schema=None) as batch_op:
        batch_op.drop_column('aforo')

    # ### end Alembic commands ###
