"""empty message

Revision ID: 68baebbe70ec
Revises: 
Create Date: 2023-03-19 23:37:45.758738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68baebbe70ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_operario', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_espacioFisico', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Integer(), nullable=True),
    sa.Column('vencida', sa.Integer(), nullable=True),
    sa.Column('fechaHora_realizada', sa.DateTime(), nullable=True),
    sa.Column('fecha_reservar', sa.DateTime(), nullable=True),
    sa.Column('hora_reservar', sa.DateTime(), nullable=True),
    sa.Column('hora_finalReservar', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    # ### end Alembic commands ###
