"""empty message

Revision ID: 7baa179c0639
Revises: f126b2d23ab2
Create Date: 2023-02-26 20:38:33.353015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baa179c0639'
down_revision = 'f126b2d23ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_operario', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('id_operario')

    # ### end Alembic commands ###
