"""empty message

Revision ID: 7c7072ff019d
Revises: 
Create Date: 2023-03-02 00:01:35.959520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7072ff019d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=False),
    sa.Column('horas_uso', sa.Integer(), nullable=True),
    sa.Column('horas_nueva_reserva', sa.Integer(), nullable=True),
    sa.Column('tiempo_espera', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_operario', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_espacioFisico', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Integer(), nullable=True),
    sa.Column('vencida', sa.Integer(), nullable=True),
    sa.Column('fecha_realizada', sa.String(), nullable=True),
    sa.Column('hora_realizada', sa.String(), nullable=True),
    sa.Column('fecha_reservar', sa.String(), nullable=True),
    sa.Column('hora_reservar', sa.String(), nullable=True),
    sa.Column('hora_finalReservar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('espacios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_regla', sa.Integer(), nullable=False),
    sa.Column('facultad', sa.String(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('reservable', sa.Integer(), nullable=True),
    sa.Column('reservado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_regla'], ['reglas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espacios_fisicos')
    op.drop_table('reservas')
    op.drop_table('reglas')
    # ### end Alembic commands ###
