"""empty message

Revision ID: 8e6ab4016845
Revises: 
Create Date: 2023-02-25 16:20:22.225109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6ab4016845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('espacios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.Column('id_bloque', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=False),
    sa.Column('horas_uso', sa.Time(), nullable=False),
    sa.Column('horas_nueva_reserva', sa.Time(), nullable=False),
    sa.Column('tiempo_espera', sa.Time(), nullable=False),
    sa.Column('reservable', sa.Boolean(), nullable=True),
    sa.Column('reservado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloques.id'], ),
    sa.ForeignKeyConstraint(['id_facultad'], ['facultades.id'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('documento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('apellido', sa.String(length=40), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('carrera', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('documento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('espacios_fisicos')
    op.drop_table('tipos')
    op.drop_table('roles')
    op.drop_table('facultades')
    op.drop_table('bloques')
    # ### end Alembic commands ###
