"""empty message

Revision ID: aaddfc272f54
Revises: 8e6ab4016845
Create Date: 2023-02-25 17:47:49.995026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaddfc272f54'
down_revision = '8e6ab4016845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espacios_fisicos', schema=None) as batch_op:
        batch_op.alter_column('aforo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('horas_uso',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('horas_nueva_reserva',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espacios_fisicos', schema=None) as batch_op:
        batch_op.alter_column('horas_nueva_reserva',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('horas_uso',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('aforo',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
