"""empty message

Revision ID: e704871ad2f0
Revises: 100394f0eff1
Create Date: 2023-02-25 22:09:58.868846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e704871ad2f0'
down_revision = '100394f0eff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultad', sa.String(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=False),
    sa.Column('horas_uso', sa.Time(), nullable=True),
    sa.Column('horas_nueva_reserva', sa.Time(), nullable=True),
    sa.Column('tiempo_espera', sa.Time(), nullable=True),
    sa.Column('reservable', sa.Boolean(), nullable=True),
    sa.Column('reservado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espacios_fisicos')
    # ### end Alembic commands ###
