"""empty message

Revision ID: e8988d464be9
Revises: aaddfc272f54
Create Date: 2023-02-25 17:49:50.743734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8988d464be9'
down_revision = 'aaddfc272f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.Column('id_bloque', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=True),
    sa.Column('horas_uso', sa.Time(), nullable=True),
    sa.Column('horas_nueva_reserva', sa.Time(), nullable=True),
    sa.Column('tiempo_espera', sa.Time(), nullable=False),
    sa.Column('reservable', sa.Boolean(), nullable=True),
    sa.Column('reservado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloques.id'], ),
    sa.ForeignKeyConstraint(['id_facultad'], ['facultades.id'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espacios_fisicos')
    # ### end Alembic commands ###
