"""empty message

Revision ID: fa80815a493e
Revises: e704871ad2f0
Create Date: 2023-02-26 00:52:11.877960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa80815a493e'
down_revision = 'e704871ad2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultad', sa.String(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=False),
    sa.Column('horas_uso', sa.DateTime(), nullable=True),
    sa.Column('horas_nueva_reserva', sa.DateTime(), nullable=True),
    sa.Column('tiempo_espera', sa.DateTime(), nullable=True),
    sa.Column('reservable', sa.Boolean(), nullable=True),
    sa.Column('reservado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_espacioFisico', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('vencida', sa.Boolean(), nullable=True),
    sa.Column('fecha_realizada', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('espacios_fisicos')
    # ### end Alembic commands ###
